name: Ci-Build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        target:
          - x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        run: rustup update stable
      - name: Get version
        id: get-version
        run: |
          echo "version=$(rustc --version)" >> $GITHUB_OUTPUT
        shell: bash
      - name: Setup Docker Cache
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ steps.get-version.outputs.version }}-${{ matrix.target }}
      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
      - name: Setup Cache
        uses: Swatinem/rust-cache@v2
      - name: build
        run: cargo build --profile githubci
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: InfinitySpread-${{ matrix.target }}
          path: target/${{ matrix.target }}/githubci/libInfinitySpread.so
          
